import calender
from tkinter import *
def showCalender():
    gui=Tk()
    gui.config(background='grey')
    gui.title("calender for the year")
    gui.geometry("550*600")
    year=int(year_field.get())
    gui_content=calender.calender(year)
    Calyear=Label(gui,text=gui_content,font="consolas 10 bold")
    calyear.grid(row=5,column=1,padx=20)
    gui.mainloop()
    if_name_=='_main_':
    new=Tk()
    new.config(background='grey')
    new.title("calender")
    new.geometry("250*140")
    cal=Lable(new,text="enter year",bg='dark grey')
    year_feield=Entry(new)
    button=Button(new,text='Show Calender',fg='Black',bg='Blue',command=showCalender)
    cal.grid(row=1,column=1)
    year.grid(row=2,column=1)
    year_field.grid(row=3,column=1)
    button.grid(row=4,column=1)
    Exit.grid(row=6,column=1)
    new.mainloop()
